<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-I33T45KV" failures="1" tests="1" name="Default test(failed)" time="7.081" errors="0" timestamp="2022-12-30T23:47:48 IST">
  <testcase classname="JavaPackage.Assertion2" name="test5" time="7.049">
    <failure type="java.lang.AssertionError" message="expected [Sorrrry, we don&amp;apos;t recognize this email.] but found [Sorry, we don&amp;apos;t recognize this email.]">
      <![CDATA[java.lang.AssertionError: expected [Sorrrry, we don't recognize this email.] but found [Sorry, we don't recognize this email.]
at JavaPackage.Assertion2.test5(Assertion2.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- Default test(failed) -->
